### ISSUE TITLE
storageclass example?

### ISSUE THREAD

**Issue by jamstar** [kairen/kube-ansible#46]
first of all, i love your project. it was quite helpful for me to get k8s with hyperconverged ceph running in ansible.   Do you have an example storageclass based on this project? I have been trying to create one but im not having luck.  it gives an error about incorrect secrets and  i have been trying a different number of id and secret names and have not had luck.  I attached one version of the example below.
```
---
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
   name: normal
provisioner: kubernetes.io/rbd
parameters:
  monitors: 10.10.73.3:6789,10.10.44.4:6789,10.10.39.4:6789
  adminId: admin
  adminSecretName: ceph-conf-combined
  adminSecretNamespace: ceph
  pool: kube
  userId: client
  userSecretName: ceph-client-key
```

Appreciate any help you can give.
